version: 2.1

jobs:
  nox:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/signalfx-python-tracing
    resource_class: medium
    parameters:
      session:
        type: string
      cli_params:
        default: "-k"
        type: string
    steps:
      - checkout
      - &pyenv-versions
        run:
          name: Pyenv
          command: pyenv versions
      - &pyenv-set-local
        run:
          name: Pyenv
          command: pyenv local 2.7.12 3.5.2 3.6.5 3.7.0
      - &install-nox
        run:
          name: Install nox
          command: python3.7 -m pip install nox
      - restore_cache:
         keys:
           - nox-v1-<<parameters.session>>-{{ checksum "noxfile.py" }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: <<parameters.session>>
          command: python3.7 -m nox <<parameters.cli_params>> <<parameters.session>> 
      - save_cache:
         key: nox-v1-<<parameters.session>>-{{ checksum "noxfile.py" }}-{{ checksum "requirements-test.txt" }}
         paths:
           - .nox 


workflows:
  version: 2
  build:
    jobs:
      - nox:
          name: lint 
          session: flake8
          cli_params: -s
      - nox:
          name: unit 
          session: unit 
          cli_params: -s
      - nox:
          name: jaeger bootstrap
          session: jaeger_via_bootstrap
          cli_params: -s
      - nox:
          name: tornado
          session: tornado
      - nox:
          name: requests
          session: requests
      - nox:
          name: redis
          session: redis
      - nox:
          name: pymongo
          session: pymongo
      - nox:
          name: pymysql
          session: pymysql
      #- nox:
      #    name: psycopg2 
      #    session: psycopg2 
      - nox:
          name: flask
          session: flask
      - nox:
          name: falcon 
          session: falcon 
      - nox:
          name: django
          session: django
      - nox:
          name: celery
          session: celery
      #- nox:
      #    name: elasticsearch 
      #    session: elasticsearch 
      - nox:
          name: logging 
          session: logging 

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nox:
          name: lint
          session: flake8 
          cli_params: -s
      - nox:
          name: unit
          session: unit
          cli_params: -s
      - nox:
          name: jaeger bootstrap
          session: jaeger_via_bootstrap
          cli_params: -s
      - nox:
          name: jaeger extras
          session: jaeger_via_extras
          cli_params: -s
      - nox:
          name: tornado
          session: tornado
      - nox:
          name: requests
          session: requests
      - nox:
          name: redis
          session: redis
      - nox:
          name: pymongo
          session: pymongo
      - nox:
          name: pymysql
          session: pymysql
      #- nox:
      #    name: psycopg2 
      #    session: psycopg2 
      - nox:
          name: flask
          session: flask
      - nox:
          name: falcon 
          session: falcon 
      - nox:
          name: django
          session: django
      - nox:
          name: celery
          session: celery
      #- nox:
      #    name: elasticsearch 
      #    session: elasticsearch 
      - nox:
          name: logging 
          session: logging 
